# Generated by Django 2.0.7 on 2019-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
