# Generated by Django 2.0.7 on 2019-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.TextField(blank=True),
        ),
    ]
