# Generated by Django 2.0.7 on 2019-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190314_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.TextField(),
        ),
    ]
